"""Oracle correctness on HAND-BUILT fixtures (not generator-produced).

Checklist A requires a handful of hand-constructed input/gold pairs with
*independently verified* expected output, asserting the oracle returns
the exact expected string. For c11 the concrete fixtures are the ceiling
prompt's worked examples, regenerated through ``rfc8785.dumps`` and
compared byte-for-byte.

Every fixture below is written by hand -- its expected canonical string is
stated as a literal, independently derived from the RFC 8785 rules, not
read back from the generator. So this file exercises the oracle as a
genuine independent check and would catch an oracle that had silently
become a re-derivation of generator internals.
"""

from __future__ import annotations

import json

import pytest
import rfc8785

from whetstone_envs.c11 import oracle
from whetstone_envs.c11.prompts import WORKED_EXAMPLE_INPUTS

# Ceiling-prompt worked examples: (messy input, expected canonical).
# The expected strings are hand-verified JCS forms; the test also
# regenerates them through ``rfc8785.dumps`` to pin the real oracle bytes.
_WORKED_EXAMPLES: list[tuple[str, str]] = [
    ('{"b": 2, "a": 1}', '{"a":1,"b":2}'),
    ('{"x": 1.0, "y": 1e2, "z": -0}', '{"x":1,"y":100,"z":0}'),
    ('{"s": "line1\\nline2", "t": "π"}', '{"s":"line1\\nline2","t":"π"}'),
    (
        '{"nested": {"d": 4, "c": 3}, "arr": [true, null]}',
        '{"arr":[true,null],"nested":{"c":3,"d":4}}',
    ),
    ('{"large": 1e30}', '{"large":1e+30}'),
]

# Additional hand-built fixtures, one per JCS sub-rule the strata stress.
_SUBRULE_FIXTURES: list[tuple[str, str]] = [
    # S1 whitespace only: canonical strips insignificant whitespace.
    ('{ "a": 1, "b": 2 }', '{"a":1,"b":2}'),
    # S2 key sort at every level.
    ('{"c": 1, "a": {"z": 1, "b": 2}}', '{"a":{"b":2,"z":1},"c":1}'),
    # S3 number canonicalization includes decimal and exponent thresholds.
    (
        '{"n": [-0.0, 1.50, 1e2, 100.0, 1e30]}',
        '{"n":[0,1.5,100,100,1e+30]}',
    ),
    # S4 escaping: tab -> \t, quote -> \", control U+0001 -> .
    ('{"k": "a\\tb\\"c\\u0001d"}', '{"k":"a\\tb\\"c\\u0001d"}'),
    # S4 non-ASCII: literal UTF-8, never \u-escaped (the pi case).
    ('{"k": "café"}', '{"k":"café"}'),
    # Array element order preserved; literals exact.
    ("[true, false, null, 3, 2]", "[true,false,null,3,2]"),
]


def test_worked_examples_regenerate_byte_for_byte() -> None:
    # Spec Section 7.5: the ceiling prompt's Output strings are hand-typed
    # placeholders and must be regenerated by rfc8785.dumps on the exact
    # inputs. This asserts the oracle (which delegates to rfc8785.dumps
    # unmodified) reproduces each hand-verified canonical string exactly.
    for messy, expected in _WORKED_EXAMPLES:
        assert oracle.canonicalize(messy) == expected


def test_worked_example_inputs_match_the_prompt_module() -> None:
    # The prompt inputs and oracle-regeneration fixtures stay in lockstep.
    assert tuple(m for m, _ in _WORKED_EXAMPLES) == WORKED_EXAMPLE_INPUTS


def test_oracle_matches_raw_rfc8785_dumps() -> None:
    # The oracle must be nothing more than parse + rfc8785.dumps: compare
    # against calling the library directly on the same parsed object.
    for messy, _ in (*_WORKED_EXAMPLES, *_SUBRULE_FIXTURES):
        direct = rfc8785.dumps(json.loads(messy)).decode("utf-8")
        assert oracle.canonicalize(messy) == direct


@pytest.mark.parametrize(
    ("messy", "expected"),
    [*_WORKED_EXAMPLES, *_SUBRULE_FIXTURES],
    ids=[m for m, _ in (*_WORKED_EXAMPLES, *_SUBRULE_FIXTURES)],
)
def test_canonicalize_hand_built(messy: str, expected: str) -> None:
    assert oracle.canonicalize(messy) == expected


@pytest.mark.parametrize(
    ("messy", "expected"),
    [*_WORKED_EXAMPLES, *_SUBRULE_FIXTURES],
    ids=[m for m, _ in (*_WORKED_EXAMPLES, *_SUBRULE_FIXTURES)],
)
def test_score_1_on_exact_canonical(messy: str, expected: str) -> None:
    assert oracle.score(expected, messy) == 1
    # A messy (non-canonical) prediction scores 0.
    assert oracle.score(messy, messy) == 0


def test_score_normalizes_wrapping_fence() -> None:
    # A fenced but otherwise-correct answer still scores 1 (shared
    # normalize() strips one wrapping code fence).
    messy = '{"b": 2, "a": 1}'
    fenced = '```\n{"a":1,"b":2}\n```'
    assert oracle.score(fenced, messy) == 1


def test_score_gold_matches_score() -> None:
    messy = '{"b": 2, "a": 1}'
    gold = oracle.canonicalize(messy)
    assert oracle.score_gold(gold, gold) == 1
    assert oracle.score_gold("wrong", gold) == 0


def test_score_zero_on_uncanonicalizable_input() -> None:
    # An integer beyond the IEEE-754 safe domain cannot be canonicalized;
    # score() must return 0 rather than raise (a model response is graded).
    huge = '{"n": 12345678901234567890}'
    assert oracle.score("anything", huge) == 0
    # ...and canonicalize() itself raises loudly for the generator.
    with pytest.raises(rfc8785.CanonicalizationError):
        oracle.canonicalize(huge)


def test_score_zero_on_malformed_input() -> None:
    assert oracle.score("x", "{not valid json") == 0
    with pytest.raises(json.JSONDecodeError):
        oracle.canonicalize("{not valid json")
