"""Mint a pre-Stage-0 ``study.json`` from a committed protocol.

This is the authoring path a pre-registration needs: one command, over a
design that lives in :mod:`whetstone_envs.optim.study.protocols`, producing
the manifest a study then spends against. Nothing here decides anything --
every value is read off the protocol or recomputed from the population --
so two runs of ``init`` at the same protocol produce the same manifest, and
a manifest that disagrees with the module is a manifest someone edited.

Three things are computed rather than declared, because declaring them
would let the record drift from what the study will actually evaluate:

* the **task hashes** of all three splits, regenerated by the same pool and
  experiment builder every stage binds, so ``bound_stage_environment``'s
  population check passes against a record that was never typed by hand;
* the **pool manifest hash**, from the generated pool itself;
* the **protocol document digest**, from the file in force at init time.

What ``init`` does *not* write is the pre-registration block. That is
Stage 0's: the pinned hash covers the measured design, and minting it
before the anchors are calibrated would freeze run counts and a
``K_REPEAT`` the gate has not yet had a chance to move.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from whetstone_envs.optim.families import family_spec
from whetstone_envs.optim.rows import task_rows_from_instances
from whetstone_envs.optim.study.manifest import (
    DESIGN_PROJECTION_FULL,
    DESIGN_PROJECTION_WITHOUT_CODEX,
    ArmRecord,
    ModelsRecord,
    PopulationRecord,
    SplitRecord,
    SplitsRecord,
    StudyManifest,
    write_study_manifest,
)
from whetstone_envs.optim.study.protocols import (
    StudyProtocol,
    protocol_doc_sha256,
)
from whetstone_envs.optim.study.spec import StageId
from whetstone_envs.optim.study.stages import (
    SEED_NOTE_CONTROL_FIELD,
    SEED_NOTE_PROVIDER_ONLY,
)

if TYPE_CHECKING:
    from collections.abc import Iterable

    from whetstone_envs.instances import Instance
    from whetstone_envs.optim.study.protocols import ArmDesign

__all__ = [
    "PENDING_EVAL_CONFIG_HASH",
    "init_study",
    "study_manifest_for",
]

#: What a split's ``eval_config_hash`` says before Stage 0 has derived one.
#:
#: The real hash is a property of the eval config Stage 0 builds at the
#: measured ``K_REPEAT``, so it cannot exist in a pre-Stage-0 manifest. The
#: field is required and non-blank, so the honest value is a marker that
#: reads as unset rather than a plausible-looking digest that would later
#: be silently replaced.
PENDING_EVAL_CONFIG_HASH = "pending-stage0"


def _task_hashes(instances: Iterable[Instance]) -> tuple[str, ...]:
    return tuple(row.task_hash for row in task_rows_from_instances(instances))


def _seed_note(arm: ArmDesign) -> str:
    """Whether this arm's optimizer has a seed field of its own.

    COPRO and the identity null carry no control seed -- their only
    stochasticity is the proposer LM -- so recording them as seeded would
    imply a reproducibility the run does not have.
    """
    if arm.optimizer in {"copro", "null-identity"}:
        return SEED_NOTE_PROVIDER_ONLY
    return SEED_NOTE_CONTROL_FIELD


def _control_identity_hash(protocol: StudyProtocol, arm: ArmDesign) -> str:
    """A digest of the arm's pinned control, before it has run.

    After a run the manifest carries the run's own result hash here. Before
    one there is no result, so this records the *design* of the control --
    every pin that will shape it -- which is what makes two studies
    initialised from the same protocol comparable, and makes an edited pin
    visible as a changed hash rather than as nothing at all.
    """
    payload = {
        "arm_id": arm.arm_id,
        "optimizer": arm.optimizer,
        "demo_mode": arm.demo_mode,
        "train_size": arm.train_size,
        "val_size": arm.val_size,
        "copro_breadth": arm.copro_breadth,
        "copro_depth": arm.copro_depth,
        "miprov2_num_trials": arm.miprov2_num_trials,
        "miprov2_num_candidates": arm.miprov2_num_candidates,
        "miprov2_minibatch": arm.miprov2_minibatch,
        "miprov2_minibatch_size": arm.miprov2_minibatch_size,
        "gepa_max_metric_calls": (
            protocol.gepa_max_metric_calls if arm.optimizer == "gepa" else None
        ),
        "gepa_reflection_minibatch_size": (
            protocol.gepa_reflection_minibatch_size
            if arm.optimizer == "gepa"
            else None
        ),
        "codex_evaluate_call_cap": (
            protocol.codex_evaluate_call_cap
            if arm.optimizer == "codex"
            else None
        ),
        "task_model": protocol.task_model,
        "proposer_model": protocol.proposer_model,
        "codex_agent_model": (
            protocol.codex_agent_model if arm.optimizer == "codex" else None
        ),
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode()).hexdigest()


def _arm_records(protocol: StudyProtocol) -> tuple[ArmRecord, ...]:
    """Every arm as a manifest record, validated as a runnable spec first.

    ``to_spec`` is called for its refusals: it is where a minibatch with no
    size, or a train/val partition on an optimizer with no such concept, is
    rejected. The manifest's own ``ArmRecord`` does not check those, so an
    ``init`` that skipped this crossing could write a manifest that
    validated and then failed on its first paid arm.
    """
    for arm in protocol.arms:
        arm.to_spec(stage=StageId.STAGE2)
    return tuple(
        ArmRecord(
            arm_id=arm.arm_id,
            optimizer=arm.optimizer,
            kind=arm.kind,
            demo_mode=arm.demo_mode,
            train_size=arm.train_size,
            val_size=arm.val_size,
            # Minibatching is design, and schema v9 carries it on the arm
            # record so it round-trips into the spec every stage runs. A
            # record that said "unbatched" while the pre-registration
            # hashed a size would evaluate every trial on the whole valset
            # under a design hash claiming otherwise.
            minibatch=arm.miprov2_minibatch,
            minibatch_size=arm.miprov2_minibatch_size,
            # The rest of the pinned search shape, on the record for the
            # minibatch's reason (schema v10). Without these four the
            # rebuilt spec fell back to the runner's smoke-run defaults:
            # a 2x1 COPRO search where the design pinned 6x3, and 2
            # MIPROv2 trials where it pinned 10.
            copro_breadth=arm.copro_breadth,
            copro_depth=arm.copro_depth,
            miprov2_num_trials=arm.miprov2_num_trials,
            miprov2_num_candidates=arm.miprov2_num_candidates,
            control_identity_hash=_control_identity_hash(protocol, arm),
            seed_note=_seed_note(arm),
            runs=(),
        )
        for arm in protocol.arms
    )


def _splits_record(protocol: StudyProtocol) -> SplitsRecord:
    """The three splits, regenerated from the pinned population.

    The hashes come from the same generator and the same experiment builder
    every stage binds, so what the manifest records is what the harness
    will regenerate -- which is the whole point of recording them, and the
    thing ``_require_recorded_population`` checks before any stage spends.
    """
    family = family_spec(protocol.family)
    pool = family.generate_pool(
        n_per_stratum=protocol.n_per_stratum,
        seed_start=protocol.pool_seed_start,
    )
    split = family.build_experiment(
        pool,
        split_sizes=protocol.split_sizes,
        num_seeds=1,
        provider_call_config=None,
    ).split
    return SplitsRecord(
        internal=SplitRecord(
            size=protocol.internal_size,
            task_hashes=_task_hashes(split.internal_eval),
            eval_config_hash=PENDING_EVAL_CONFIG_HASH,
        ),
        official=SplitRecord(
            size=protocol.official_size,
            task_hashes=_task_hashes(split.official),
            eval_config_hash=PENDING_EVAL_CONFIG_HASH,
        ),
        held_out=SplitRecord(
            size=protocol.held_out_size,
            task_hashes=_task_hashes(split.held_out),
            eval_config_hash=PENDING_EVAL_CONFIG_HASH,
        ),
    )


def _population_record(protocol: StudyProtocol) -> PopulationRecord:
    """The pinned population and the content hash of its own manifest."""
    pool_manifest = family_spec(protocol.family).pool_manifest(
        n_per_stratum=protocol.n_per_stratum,
        seed_start=protocol.pool_seed_start,
    )
    return PopulationRecord(
        family=protocol.family,
        # From the manifest the family just built, not restated by the
        # protocol: the generator version describes the pool that was
        # generated, so the thing that generated it is what should name it.
        generator_version=pool_manifest.generator_version,
        n_per_stratum=protocol.n_per_stratum,
        pool_seed_start=protocol.pool_seed_start,
        pool_manifest_content_hash=pool_manifest.content_hash,
        stratum_counts=dict(pool_manifest.stratum_counts),
    )


def study_manifest_for(
    protocol: StudyProtocol,
    *,
    study_id: str | None = None,
    protocol_doc: Path | None = None,
    created_at: str | None = None,
) -> StudyManifest:
    """The pre-Stage-0 manifest this protocol pre-registers.

    Separated from the write so the manifest can be built and inspected --
    by a test, or by a caller pricing a design -- without a directory to
    put it in.
    """
    # The recorded path is the protocol's own by default, so a manifest
    # names the durable document rather than whatever local path a caller
    # happened to pass; the digest always comes from the file actually read.
    doc_path = (
        Path(protocol.protocol_doc_path)
        if protocol_doc is None
        else protocol_doc
    )
    recorded_doc_path = (
        protocol.protocol_doc_path
        if protocol_doc is None
        else str(protocol_doc)
    )
    digest = protocol_doc_sha256(doc_path)
    return StudyManifest(
        study_id=protocol.study_id if study_id is None else study_id,
        created_at=(
            datetime.now(UTC).isoformat() if created_at is None else created_at
        ),
        protocol_doc_path=recorded_doc_path,
        protocol_doc_sha256=digest,
        # The Step 10 study's authorising assignment *is* the protocol
        # document, so there is no second document to digest. Recorded as
        # absent rather than as the sha256 of a fixed marker string --
        # that was a digest of nothing, which read like provenance and
        # verified nothing at all.
        assignment_doc_sha256=None,
        design_projection=(
            DESIGN_PROJECTION_WITHOUT_CODEX
            if not any(arm.optimizer == "codex" for arm in protocol.arms)
            else DESIGN_PROJECTION_FULL
        ),
        population=_population_record(protocol),
        splits=_splits_record(protocol),
        models=ModelsRecord(
            task_model=protocol.task_model,
            proposer_model=protocol.proposer_model,
            temperature=protocol.temperature,
            provider=protocol.provider,
            seed_control=protocol.seed_control,
            codex_agent_model=protocol.codex_agent_model,
        ),
        arms=_arm_records(protocol),
    )


def init_study(
    study_dir: Path,
    *,
    protocol: StudyProtocol,
    study_id: str | None = None,
    protocol_doc: Path | None = None,
) -> Path:
    """Write this protocol's pre-Stage-0 manifest into ``study_dir``.

    Refuses to overwrite an existing ``study.json``:
    :func:`write_study_manifest` is called without ``replace``, so a second
    ``init`` over a study that has already calibrated raises
    :class:`~whetstone_envs.optim.study.manifest.ManifestExistsError` rather
    than silently resetting a design that evidence already refers to.
    """
    manifest = study_manifest_for(
        protocol, study_id=study_id, protocol_doc=protocol_doc
    )
    return write_study_manifest(study_dir, manifest)
